name: CI - UAT to Main (PR Request)

on:
  push:
    branches:
      - uat

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Create PR uat â†’ main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: uat
          title: "UAT â†’ Main (Approval Required)"
          body: |
            âœ… Code pushed to UAT successfully.
            ğŸ” Please review and approve to merge into MAIN.
